export const myListings = [
  {
    id: 1,
    address: "Srijana chowk, Pokhara",
    price: 5000,
    updatedAt: "3 days ago",
    img: "/assets/image_login-min.jpg",
    reserved: true,
    details: {
      wifi: true,
      bath: 2,
      parking: false,
      category: "Room",
      floor: 1,
      rooms: 2,
      nearestLandmark: "Pokhara Engineering College",
    },
  },
  {
    id: 2,
    address: "Srijana chowk, Pokhara",
    price: 25000,
    updatedAt: "1 day ago",
    img: "/assets/livingroom-min.jpg",
    reserved: false,
    details: {
      wifi: true,
      bath: 2,
      parking: false,
      category: "Apartment",
      floor: 1,
      rooms: 3,
      kitchen: 1,
      nearestLandmark: "Srijana Secondary School",
    },
  },
  {
    id: 3,
    address: "Srijana chowk, Pokhara",
    price: 5000,
    updatedAt: "3 days ago",
    img: "/assets/image_login-min.jpg",
    reserved: true,
    details: {
      wifi: true,
      bath: 2,
      parking: false,
      category: "Room",
      floor: 1,
      rooms: 2,
      nearestLandmark: "Pokhara Engineering College",
    },
  },
];
